const canvas = document.querySelector("#game-canvas");
const context = canvas.getContext("2d");
const modeButtons = document.querySelectorAll("[data-mode]");
const keys = { a: false, d: false };
const game = { mode: "wheelie", running: false, crashed: false, score: 0, best: Number(localStorage.getItem("dirtline-best") || 0), distance: 0, airTime: 0, flips: 0, lastTime: 0, width: 0, height: 0, groundY: 0, steering: 0, bike: { x: 160, y: 0, vy: 0, angle: 0, angularVelocity: 0, speed: 0 }, terrain: [] };

const colors = { ink: "#263435", green: "#367564", darkGreen: "#1e4942", orange: "#e66f42", yellow: "#f1c35e", dirt: "#a87854", dirtDark: "#79523f", sky: "#b9dbe0", cloud: "rgba(255,255,255,.55)" };
const $ = (selector) => document.querySelector(selector);

function resizeCanvas() { const bounds = canvas.getBoundingClientRect(); const ratio = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.floor(bounds.width * ratio); canvas.height = Math.floor(bounds.height * ratio); context.setTransform(ratio, 0, 0, ratio, 0, 0); game.width = bounds.width; game.height = bounds.height; game.groundY = game.height * .72; resetBike(false); buildTerrain(); draw(); }
function resetBike(clearRun = true) { if (clearRun) { game.score = 0; game.distance = 0; game.airTime = 0; game.flips = 0; } game.running = false; game.crashed = false; game.lastTime = 0; game.steering = 0; game.bike = { x: Math.min(160, game.width * .25), y: game.groundY - 28, vy: 0, angle: game.mode === "wheelie" ? -.08 : 0, angularVelocity: 0, speed: 0 }; setStatus("READY TO RIDE"); updateHud(); }
function buildTerrain() { const points = []; for (let x = 0; x < game.width + 180; x += 18) { let y = game.groundY; if (game.mode === "jumps") { const jumpX = game.width * .55; const wave = Math.max(0, 1 - Math.abs(x - jumpX) / 130); y -= wave * wave * 95; const secondWave = Math.max(0, 1 - Math.abs(x - (game.width * .9)) / 115); y -= secondWave * secondWave * 62; } points.push({ x, y }); } game.terrain = points; }
function terrainY(x) { if (!game.terrain.length) return game.groundY; const index = Math.max(0, Math.min(game.terrain.length - 2, Math.floor(x / 18))); const left = game.terrain[index]; const right = game.terrain[index + 1]; const amount = (x - left.x) / (right.x - left.x); return left.y + (right.y - left.y) * amount; }
function setMode(mode) { game.mode = mode; modeButtons.forEach((button) => button.classList.toggle("active", button.dataset.mode === mode)); $("#mode-label").textContent = mode === "wheelie" ? "WHEELIE / STREET RUN" : "JUMPS / FLIP LINE"; $("#trick-label").textContent = mode === "wheelie" ? "BALANCE" : "FLIPS"; $("#game-message").textContent = mode === "wheelie" ? "Keep the front wheel up. A leans back, D leans forward." : "Launch the jumps. A and D rotate you in the air."; resetBike(); buildTerrain(); draw(); }
function setStatus(text, live = false) { $("#run-status").textContent = text; $(".status-dot").classList.toggle("live", live); $("#canvas-message").querySelector("strong").textContent = text; $("#canvas-message").querySelector("span").textContent = game.running ? "A / D to control the bike" : "Press A or D to start riding"; }
function updateHud() { $("#score-value").textContent = Math.floor(game.score).toLocaleString(); $("#best-value").textContent = Math.floor(game.best).toLocaleString(); $("#distance-value").textContent = `${Math.floor(game.distance)} m`; $("#trick-value").textContent = game.mode === "wheelie" ? `${Math.min(100, Math.max(0, Math.round((Math.abs(game.bike.angle) / .95) * 100)))}%` : `${game.flips} flip${game.flips === 1 ? "" : "s"}`; }
function startIfNeeded() { if (game.crashed) resetBike(false); if (!game.running) { game.running = true; setStatus("RIDE LIVE", true); $("#canvas-message").style.opacity = "0"; } }
function pressKey(key, pressed) { keys[key] = pressed; if (pressed) startIfNeeded(); }
function update(delta) { const bike = game.bike; const dt = Math.min(delta / 16.67, 1.5); const steering = (keys.d ? 1 : 0) - (keys.a ? 1 : 0); game.steering += (steering - game.steering) * Math.min(1, .18 * dt); if (!game.running) return; if (game.mode === "wheelie") updateWheelie(bike, game.steering, dt); else updateJumps(bike, game.steering, dt); game.distance += bike.speed * .045 * dt; game.score += bike.speed * .018 * dt; updateHud(); }
function updateWheelie(bike, steering, dt) { bike.speed = Math.min(7.5, bike.speed + .035 * dt); bike.angularVelocity += steering * .0052 * dt; bike.angularVelocity *= Math.pow(.88, dt); bike.angle += bike.angularVelocity * dt; if (!keys.a && !keys.d) bike.angle += .0008 * dt; bike.y = terrainY(bike.x) - 33; if (bike.angle > 1.16 || bike.angle < -.88) crash("Too far forward. Find the balance point."); if (Math.abs(bike.angle) < .98) game.score += Math.max(0, .98 - Math.abs(bike.angle)) * .35 * dt; bike.x += bike.speed * dt; if (bike.x > game.width + 55) bike.x = -55; }
function updateJumps(bike, steering, dt) { bike.speed = Math.min(8.5, bike.speed + .045 * dt); const ground = terrainY(bike.x); const grounded = bike.y >= ground - 29 && bike.vy >= 0; if (grounded) { bike.y = ground - 29; if (game.airTime > 0) { const rotation = Math.abs(bike.angle % (Math.PI * 2)); const clean = rotation < .28 || Math.abs(rotation - Math.PI * 2) < .28; if (!clean) { crash("Hard landing. Match the bike to the ramp."); return; } game.score += game.flips * 120 + 80; game.airTime = 0; game.flips = 0; } bike.vy = 0; bike.angularVelocity = -bike.angle * .12; } else { game.airTime += dt; bike.angularVelocity += steering * .012 * dt; bike.angularVelocity *= .995; bike.angle += bike.angularVelocity * dt; bike.vy += .34 * dt; if (Math.abs(bike.angle) > Math.PI * 2.4) crash("Too many rotations. Bring it back around."); } bike.y += bike.vy * dt; bike.x += bike.speed * dt; if (bike.x > game.width + 30) bike.x = 150; }
function crash(message) { game.running = false; game.crashed = true; game.best = Math.max(game.best, Math.floor(game.score)); localStorage.setItem("dirtline-best", game.best); setStatus("RUN OVER"); $("#game-message").textContent = `${message} Press A or D to restart.`; $("#canvas-message").style.opacity = "1"; $("#canvas-message").querySelector("span").textContent = "Press A or D to restart"; }
function loop(timestamp) { if (!game.lastTime) game.lastTime = timestamp; update(timestamp - game.lastTime); game.lastTime = timestamp; draw(); requestAnimationFrame(loop); }
function draw() { context.clearRect(0, 0, game.width, game.height); drawBackground(); drawTerrain(); drawBike(); }
function drawBackground() { const gradient = context.createLinearGradient(0, 0, 0, game.height); gradient.addColorStop(0, colors.sky); gradient.addColorStop(1, "#eaf1df"); context.fillStyle = gradient; context.fillRect(0, 0, game.width, game.height); context.fillStyle = colors.cloud; context.beginPath(); context.arc(game.width * .17, game.height * .22, 30, 0, Math.PI * 2); context.arc(game.width * .22, game.height * .2, 44, 0, Math.PI * 2); context.arc(game.width * .28, game.height * .23, 27, 0, Math.PI * 2); context.fill(); context.fillStyle = "rgba(54,117,100,.2)"; context.beginPath(); context.moveTo(0, game.groundY); context.quadraticCurveTo(game.width * .2, game.height * .5, game.width * .45, game.groundY); context.quadraticCurveTo(game.width * .7, game.height * .55, game.width, game.groundY); context.lineTo(game.width, game.height); context.lineTo(0, game.height); context.fill(); }
function drawTerrain() { const points = game.terrain; if (!points.length) return; context.beginPath(); context.moveTo(0, game.height); context.lineTo(points[0].x, points[0].y); points.forEach((point) => context.lineTo(point.x, point.y)); context.lineTo(game.width, game.height); context.closePath(); context.fillStyle = colors.dirt; context.fill(); context.beginPath(); context.moveTo(points[0].x, points[0].y); points.forEach((point) => context.lineTo(point.x, point.y)); context.strokeStyle = colors.dirtDark; context.lineWidth = 5; context.stroke(); context.strokeStyle = "rgba(255,255,255,.16)"; context.lineWidth = 2; for (let x = 20; x < game.width; x += 75) { context.beginPath(); context.moveTo(x, terrainY(x) + 24); context.lineTo(x + 22, terrainY(x) + 18); context.stroke(); } }
function drawBike() { const bike = game.bike; context.save(); context.translate(bike.x, bike.y); context.rotate(bike.angle); const rearWheel = { x: -32, y: 20 }; const frontWheel = { x: 34, y: 20 }; drawWheel(rearWheel.x, rearWheel.y); drawWheel(frontWheel.x, frontWheel.y); context.lineCap = "round"; context.lineJoin = "round";
	// A compact electric enduro silhouette: battery, motor, chassis, fork, and plastics.
	context.strokeStyle = "#172b2b"; context.lineWidth = 5; context.beginPath(); context.moveTo(rearWheel.x, rearWheel.y); context.lineTo(-10, -3); context.lineTo(27, 2); context.lineTo(frontWheel.x, frontWheel.y); context.moveTo(-10, -3); context.lineTo(4, 21); context.lineTo(rearWheel.x, rearWheel.y); context.moveTo(4, 21); context.lineTo(27, 2); context.stroke();
	context.fillStyle = "#283f3d"; context.beginPath(); context.roundRect(-8, -7, 25, 28, 3); context.fill(); context.fillStyle = "#9bb8a3"; context.fillRect(-4, -3, 17, 18); context.fillStyle = "#173b38"; context.fillRect(-1, 0, 11, 3); context.fillRect(-1, 7, 11, 3);
	context.fillStyle = colors.orange; context.beginPath(); context.moveTo(-23, -11); context.lineTo(-3, -16); context.lineTo(18, -10); context.lineTo(27, 3); context.lineTo(7, 0); context.lineTo(-9, 5); context.lineTo(-22, 1); context.closePath(); context.fill();
	context.fillStyle = "#f4f0e8"; context.beginPath(); context.moveTo(-20, -11); context.lineTo(-4, -15); context.lineTo(5, -10); context.lineTo(-7, -5); context.closePath(); context.fill(); context.fillStyle = "#e66f42"; context.fillRect(-13, -14, 18, 3);
	context.strokeStyle = "#f1c35e"; context.lineWidth = 3; context.beginPath(); context.moveTo(26, 1); context.lineTo(38, -17); context.lineTo(43, 17); context.stroke(); context.strokeStyle = "#d9e0d4"; context.lineWidth = 2; context.beginPath(); context.moveTo(29, 1); context.lineTo(40, -16); context.moveTo(33, 3); context.lineTo(43, -14); context.stroke();
	context.strokeStyle = "#172b2b"; context.lineWidth = 4; context.beginPath(); context.moveTo(38, -17); context.lineTo(47, -22); context.lineTo(53, -19); context.stroke(); context.fillStyle = "#f1c35e"; context.beginPath(); context.arc(43, -15, 4, 0, Math.PI * 2); context.fill();
	context.fillStyle = "#263435"; context.beginPath(); context.moveTo(-5, -18); context.lineTo(16, -18); context.lineTo(23, -12); context.lineTo(8, -9); context.closePath(); context.fill(); context.fillStyle = "#e66f42"; context.fillRect(4, -19, 13, 2);
	context.fillStyle = "#f1c35e"; context.beginPath(); context.arc(7, -29, 8, 0, Math.PI * 2); context.fill(); context.fillStyle = "#172b2b"; context.beginPath(); context.arc(7, -31, 8, Math.PI, Math.PI * 2); context.fill(); context.fillStyle = "#b9dbe0"; context.fillRect(10, -29, 5, 2); context.strokeStyle = "#263435"; context.lineWidth = 3; context.beginPath(); context.moveTo(1, -21); context.lineTo(-7, -12); context.moveTo(12, -21); context.lineTo(18, -10); context.stroke(); context.restore(); }
function drawWheel(x, y) { context.fillStyle = "#172b2b"; context.beginPath(); context.arc(x, y, 16, 0, Math.PI * 2); context.fill(); context.strokeStyle = "#111f20"; context.lineWidth = 3; for (let spoke = 0; spoke < 8; spoke += 1) { const angle = spoke * Math.PI / 4; context.beginPath(); context.moveTo(x + Math.cos(angle) * 4, y + Math.sin(angle) * 4); context.lineTo(x + Math.cos(angle) * 12, y + Math.sin(angle) * 12); context.stroke(); } context.strokeStyle = "#d5dfd5"; context.lineWidth = 3; context.beginPath(); context.arc(x, y, 8, 0, Math.PI * 2); context.stroke(); context.fillStyle = "#f1c35e"; context.beginPath(); context.arc(x, y, 3, 0, Math.PI * 2); context.fill(); }

modeButtons.forEach((button) => button.addEventListener("click", () => setMode(button.dataset.mode)));
window.addEventListener("resize", resizeCanvas);
window.addEventListener("keydown", (event) => { const key = event.key.toLowerCase(); if (key === "a" || key === "d") { event.preventDefault(); pressKey(key, true); } });
window.addEventListener("keyup", (event) => { const key = event.key.toLowerCase(); if (key === "a" || key === "d") { event.preventDefault(); pressKey(key, false); } });
document.querySelectorAll("[data-key]").forEach((button) => { const key = button.dataset.key; button.addEventListener("pointerdown", () => pressKey(key, true)); button.addEventListener("pointerup", () => pressKey(key, false)); button.addEventListener("pointerleave", () => pressKey(key, false)); });
$("#reset-run").addEventListener("click", () => { resetBike(); $("#canvas-message").style.opacity = "1"; });
setMode("wheelie"); resizeCanvas(); requestAnimationFrame(loop);
